Feature/creation dockerfile
derniercri/docker-vue3 pull request #1
Opened 2022-06-09 16:13 UTC by AnassAoulad

2022-06-09 16:17 UTC, Jean-Serge requested changes
_(c'est un début)_

2022-06-09 16:17 UTC, Jean-Serge commented on Dockerfile
> +FROM node:latest
Pas de latest pour un conteneur de prod. Faut fixer une version de Node (au pire à valider avec Martin)

2022-06-09 16:17 UTC, Jean-Serge commented on Dockerfile
> +EXPOSE 3000
En vrai ça ça va. mais ce serait bien d'env faire une var d'env

2022-06-09 17:41 UTC, AnassAoulad commented on Dockerfile
> +WORKDIR /creation-docker-vue3
Lorsque tu dis root tu parle du WORKDIR ?

2022-06-09 18:03 UTC, AnassAoulad commented on Dockerfile
> +WORKDIR /creation-docker-vue3
Lorsque tu dis root tu parle du WORKDIR ?

2022-06-10 08:43 UTC, XavierBuisson commented on Dockerfile
> +WORKDIR /creation-docker-vue3
Lancer un conteneur avec l'utilisateur root est une faille de securite grave. Avec ces droits, tu peux plus facilement sortir du contexte du conteneur ou obtenir des informations sur le systeme et l'attaquer.

2022-06-13 14:59 UTC, Jean-Serge approved these changes
C'est chouette, maintenant j'aimerais bien voir du multi-stage docker. Ça me semble plutôt approprié

2022-06-13 14:59 UTC, Jean-Serge commented on Dockerfile
> +COPY package*.json .
T'utilises `yarn` dans le reste du fichier 😬

2022-06-13 15:14 UTC, AnassAoulad commented on Dockerfile
> +COPY package*.json .
Oui, tu pense que c'est mieux `npm` ?

2022-06-14 06:28 UTC, AnassAoulad commented
> C'est chouette, maintenant j'aimerais bien voir du multi-stage docker. Ça me semble plutôt approprié

J'essayerai le multi-stage sur une autre branche

2022-06-14 06:28 UTC, merged

2022-06-14 07:16 UTC, Jean-Serge commented on Dockerfile
> +COPY package*.json .
Non c'est juste que du coup t'ajoutes pas le `yarn.lock` 😉